export const courses = [
  {
    id: "c1b6e2a4-d5f8-4e3a-b9c7-1d2e3f4a5b6c",
    teacherId: "t1",
    teacherName: "John Smith",
    title: "Introduction to Web Development",
    description:
      "Learn the fundamentals of HTML, CSS, and JavaScript to build modern websites.",
    image: "https://example.com/images/web-dev-intro.jpg",
    price: 4999,
    category: "Web Development",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "a2c4e6b8-1d3f-5e7g-9h2i-4j5k6l7m8n9p",
    teacherId: "t1",
    teacherName: "John Smith",
    title: "Python Programming Masterclass",
    description:
      "Master Python programming from basics to advanced concepts including OOP and APIs.",
    image: "https://example.com/images/python-master.jpg",
    price: 7999,
    category: "Programming",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "f9e8d7c6-b5a4-3210-9876-5432dcba1098",
    teacherId: "t2",
    teacherName: "Sarah Johnson",
    title: "Data Science Fundamentals",
    description:
      "Introduction to data analysis, visualization, and machine learning basics.",
    image: "https://example.com/images/data-science.jpg",
    price: 8999,
    category: "Data Science",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "b1c2d3e4-f5g6-7h8i-9j0k-l1m2n3o4p5q",
    teacherId: "t3",
    teacherName: "Michael Chen",
    title: "React.js for Beginners",
    description: "Build modern user interfaces with React.js framework.",
    image: "https://example.com/images/react-basics.jpg",
    price: 5999,
    category: "Web Development",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "h7i8j9k0-l1m2-n3o4-p5q6-r7s8t9u0v1w",
    teacherId: "t4",
    teacherName: "Emily Parker",
    title: "UI/UX Design Principles",
    description:
      "Learn essential design principles and tools for creating great user experiences.",
    image: "https://example.com/images/uiux-design.jpg",
    price: 6999,
    category: "Design",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "x2y3z4a5-b6c7-d8e9-f0g1-h2i3j4k5l6m",
    teacherId: "t1",
    teacherName: "John Smith",
    title: "Advanced JavaScript Patterns",
    description:
      "Deep dive into JavaScript design patterns and advanced concepts.",
    image: "https://example.com/images/js-advanced.jpg",
    price: 9999,
    category: "Programming",
    level: "Advanced",
    status: "Published",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-25"),
  },
  {
    id: "m9n8o7p6-q5r4-s3t2-u1v0-w9x8y7z6a5",
    teacherId: "t5",
    teacherName: "Alex Thompson",
    title: "Mobile App Development with Flutter",
    description:
      "Create cross-platform mobile applications using Flutter framework.",
    image: "https://example.com/images/flutter-dev.jpg",
    price: 7999,
    category: "Mobile Development",
    level: "Intermediate",
    status: "Draft",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "b4c5d6e7-f8g9-h0i1-j2k3-l4m5n6o7p8",
    teacherId: "t6",
    teacherName: "David Wilson",
    title: "DevOps Essentials",
    description: "Learn the fundamentals of DevOps practices and tools.",
    image: "https://example.com/images/devops.jpg",
    price: 8999,
    category: "DevOps",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "q9r8s7t6-u5v4-w3x2-y1z0-a9b8c7d6e5",
    teacherId: "t2",
    teacherName: "Sarah Johnson",
    title: "Machine Learning with Python",
    description:
      "Practical approach to machine learning using Python and popular libraries.",
    image: "https://example.com/images/ml-python.jpg",
    price: 12999,
    category: "Data Science",
    level: "Advanced",
    status: "Published",
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "f4g5h6i7-j8k9-l0m1-n2o3-p4q5r6s7t8",
    teacherId: "t6",
    teacherName: "David Wilson",
    title: "Cloud Computing with AWS",
    description: "Master AWS services and cloud architecture principles.",
    image: "https://example.com/images/aws-cloud.jpg",
    price: 9999,
    category: "Cloud Computing",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "u9v8w7x6-y5z4-a3b2-c1d0-e9f8g7h6i5",
    teacherId: "t7",
    teacherName: "Rachel Kim",
    title: "Cybersecurity Fundamentals",
    description: "Introduction to cybersecurity concepts and best practices.",
    image: "https://example.com/images/cybersecurity.jpg",
    price: 7999,
    category: "Security",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "j4k5l6m7-n8o9-p0q1-r2s3-t4u5v6w7x8",
    teacherId: "t3",
    teacherName: "Michael Chen",
    title: "Node.js Backend Development",
    description: "Build scalable backend applications with Node.js.",
    image: "https://example.com/images/nodejs-backend.jpg",
    price: 8999,
    category: "Web Development",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-25"),
  },
  {
    id: "y9z8a7b6-c5d4-e3f2-g1h0-i9j8k7l6m5",
    teacherId: "t8",
    teacherName: "Mark Anderson",
    title: "Blockchain Development",
    description:
      "Learn to build decentralized applications and smart contracts.",
    image: "https://example.com/images/blockchain.jpg",
    price: 14999,
    category: "Blockchain",
    level: "Advanced",
    status: "Draft",
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-30"),
  },
  {
    id: "n4o5p6q7-r8s9-t0u1-v2w3-x4y5z6a7b8",
    teacherId: "t9",
    teacherName: "Lisa Brown",
    title: "Game Development with Unity",
    description: "Create 2D and 3D games using Unity game engine.",
    image: "https://example.com/images/unity-games.jpg",
    price: 8999,
    category: "Game Development",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-04-05"),
  },
  {
    id: "c9d8e7f6-g5h4-i3j2-k1l0-m9n8o7p6q5",
    teacherId: "t10",
    teacherName: "James Martinez",
    title: "Digital Marketing Essentials",
    description: "Master the fundamentals of digital marketing and SEO.",
    image: "https://example.com/images/digital-marketing.jpg",
    price: 6999,
    category: "Marketing",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-03-25"),
    updatedAt: new Date("2024-04-10"),
  },
  {
    id: "r4s5t6u7-v8w9-x0y1-z2a3-b4c5d6e7f8",
    teacherId: "t6",
    teacherName: "David Wilson",
    title: "Docker and Kubernetes",
    description: "Learn container orchestration with Docker and Kubernetes.",
    image: "https://example.com/images/docker-k8s.jpg",
    price: 10999,
    category: "DevOps",
    level: "Advanced",
    status: "Published",
    createdAt: new Date("2024-03-30"),
    updatedAt: new Date("2024-04-15"),
  },
  {
    id: "g9h8i7j6-k5l4-m3n2-o1p0-q9r8s7t6u5",
    teacherId: "t3",
    teacherName: "Michael Chen",
    title: "Vue.js Framework",
    description: "Build reactive web applications with Vue.js framework.",
    image: "https://example.com/images/vuejs.jpg",
    price: 7999,
    category: "Web Development",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "v4w5x6y7-z8a9-b0c1-d2e3-f4g5h6i7j8",
    teacherId: "t11",
    teacherName: "Sophie Taylor",
    title: "SQL Database Design",
    description: "Master database design principles and SQL queries.",
    image: "https://example.com/images/sql-design.jpg",
    price: 6999,
    category: "Database",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-04-10"),
    updatedAt: new Date("2024-04-25"),
  },
  {
    id: "k9l8m7n6-o5p4-q3r2-s1t0-u9v8w7x6y5",
    teacherId: "t12",
    teacherName: "Daniel Lee",
    title: "Artificial Intelligence Ethics",
    description: "Explore ethical considerations in AI development.",
    image: "https://example.com/images/ai-ethics.jpg",
    price: 8999,
    category: "Artificial Intelligence",
    level: "Advanced",
    status: "Draft",
    createdAt: new Date("2024-04-15"),
    updatedAt: new Date("2024-04-30"),
  },
  {
    id: "z4a5b6c7-d8e9-f0g1-h2i3-j4k5l6m7n8",
    teacherId: "t1",
    teacherName: "John Smith",
    title: "TypeScript Advanced Concepts",
    description: "Deep dive into TypeScript features and best practices.",
    image: "https://example.com/images/typescript.jpg",
    price: 8999,
    category: "Programming",
    level: "Advanced",
    status: "Published",
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-05-05"),
  },
  {
    id: "o9p8q7r6-s5t4-u3v2-w1x0-y9z8a7b6c5",
    teacherId: "t3",
    teacherName: "Michael Chen",
    title: "GraphQL API Development",
    description: "Build efficient APIs using GraphQL specification.",
    image: "https://example.com/images/graphql.jpg",
    price: 9999,
    category: "Web Development",
    level: "Advanced",
    status: "Published",
    createdAt: new Date("2024-04-25"),
    updatedAt: new Date("2024-05-10"),
  },
  {
    id: "d4e5f6g7-h8i9-j0k1-l2m3-n4o5p6q7r8",
    teacherId: "t13",
    teacherName: "Emma White",
    title: "Software Testing Fundamentals",
    description: "Learn essential software testing methodologies and tools.",
    image: "https://example.com/images/testing.jpg",
    price: 6999,
    category: "Quality Assurance",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-04-30"),
    updatedAt: new Date("2024-05-15"),
  },
  {
    id: "s9t8u7v6-w5x4-y3z2-a1b0-c9d8e7f6g5",
    teacherId: "t14",
    teacherName: "Ryan Garcia",
    title: "iOS App Development",
    description:
      "Create native iOS applications using Swift programming language.",
    image: "https://example.com/images/ios-dev.jpg",
    price: 11999,
    category: "Mobile Development",
    level: "Intermediate",
    status: "Published",
    createdAt: new Date("2024-05-05"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: "h4i5j6k7-l8m9-n0o1-p2q3-r4s5t6u7v8",
    teacherId: "t4",
    teacherName: "Emily Parker",
    title: "3D Modeling with Blender",
    description: "Learn 3D modeling and animation using Blender software.",
    image: "https://example.com/images/blender-3d.jpg",
    price: 7999,
    category: "Design",
    level: "Beginner",
    status: "Published",
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-05-25"),
  },
  {
    id: "w9x8y7z6-a5b4-c3d2-e1f0-g9h8i7j6k5",
    teacherId: "t6",
    teacherName: "David Wilson",
    title: "Microservices Architecture",
    description: "Design and implement microservices-based applications.",
    image: "https://example.com/images/microservices.jpg",
    price: 12999,
    category: "Software Architecture",
    level: "Advanced",
    status: "Published",
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-05-30"),
  },
];
